### ISSUE TITLE
Sulu UI backend sorting is a bit confusing

### ISSUE THREAD

**Issue by crash0verride** [sulu-cmf/sulu-standard#315]
The Sulu UI backend sorting is a bit confusing, in my opinion the most important content from a user perspective is:
1) Web-Spaces (in Web-Spaces: 1. Homepage 2. Content)
2) Assets
3) CRM
4) Settings

![sulu-ui-backend-sortation](https://cloud.githubusercontent.com/assets/3469973/4589644/788c4fba-5056-11e4-8ba6-5dca3e1d2fb4.gif)

**Comment by berndhep** [comment]
The reason for the sorting is, that if you have multiple webspaces the other modules will be pushed down. With many webspaces even out of sight. That's why we put them on the bottom. The sorting within the webspace module will be changed so the "Homepage" will be fist, followed by "Content". Which is the more obvious solution.

**Comment by danrot** [comment]
In that case this issue will be fixed by https://github.com/sulu-cmf/sulu/pull/789

**Comment by wachterjohannes** [comment]
That PR fixes only the homepage/content order, not the order of the sections!

**Comment by danrot** [comment]
As Bernd has described it's the only change we will apply, so it will be fixed afterwards.
